### PR TITLE
Add filtering to metrics script

### PR DESCRIPTION
**Pull request by ethowitz**
In this PR, I:
* Added a `--filter-queries` flag that supports piping in output from `SHOW CACHES` or `SHOW PROXIED QUERIES` to filter the script output
* Switched over to using [prometheus-client](https://pypi.org/project/prometheus-client) to make our parsing of the metrics more robust
* Added a `requirements.txt` to ease the setup process for the script and pin dependency versions to prevent unintended updates with breaking changes

Here's the workflow I've been testing with:
* Create a table and add some data
* Start up ReadySet in explicit mode with `--query-log` and `--query-log-ad-hoc`
* Make some queries against ReadySet
* Create at least one cache based on a query shown in `SHOW PROXIED QUERIES`
* Run some queries against that cache
* Run the script with `SHOW CACHES` piped in to view the latency differences in the queries we started caching

### CODE REVIEW

**Review by imeyer — APPROVED** [review]
LGTM

**Review by jseldess — APPROVED** [review]
LGTM, too. 

You should probably update https://github.com/readysettech/docs/blob/main/docs/guides/cache/profile-queries.md#examine-per-query-metrics as well.

**Comment by ethowitz** [comment]
Thanks for the reviews!

@jseldess Updated those docs -- let me know what you think!

**Comment by jseldess** [comment]
LGTM, @ethowitz. Feel free to merge!

**Pull request merged**
